---
ID: "e86c0662-00e3-4fb7-8300-d97f035554ef"
Parent: "a1818bb3-8a07-4ae1-8d30-da6b050fd75e"
Template: "ea8a3f26-9ccd-443a-95f5-71b868a94bd0"
Path: /sitecore/system/Settings/Feature/Demo Shared SXA Sites/SitecoreDemo/Account/Sitecore Demo Account/Add Security Settings
DB: master
SharedFields:
- ID: "4795a7c6-08a9-4248-86c3-d460062c3a22"
  Hint: Location
  Type: Treelist
  Value: "{6A8A971B-01BC-4749-9EF5-10C69BBA73FE}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Type: Treelist
  Value: "{233D4D7D-5BFE-4DC9-BEA7-79BE7F16EAD4}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191009T150549Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
