---
ID: "9f3edf2a-f513-4cbd-b5df-b4d01bd0743f"
Parent: "60c2f379-9ffd-4aa6-9d6d-87494aceeddd"
Template: "60c2f379-9ffd-4aa6-9d6d-87494aceeddd"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Global Pages/L2 Content Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171117T212543Z
