---
ID: "df4ffc8a-43d8-4fc2-a41c-30d21c07a168"
Parent: "eea2a34f-00da-4635-9988-0d951b753c89"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Demo Shared SXA Sites/LighthouseLifestyle/Product Thumbnails
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 350
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190411T202227Z
