---
ID: "4987bf95-424e-48c5-b5cd-4b54f3e62d2e"
Parent: "897f96b4-3a21-4877-9f63-8c3b7c9da4b9"
Template: "5203732f-9512-4ade-8e02-0cb085c10454"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Settings/Site Grouping/LighthouseFinancial/CORS/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200826T152031Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Casey
