---
ID: "7835daa7-6962-4bad-bab0-9f402c3f9de2"
Parent: "c2c6dd9f-8bf0-4f92-a5a4-a811a1fd3741"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Settings/Datasource Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200122T193206Z
