---
ID: "1c9da44d-5640-4315-a413-f899ec7d8e7c"
Parent: "0fda5249-d9b4-4d1c-8b92-ab02e541a3ff"
Template: "0fda5249-d9b4-4d1c-8b92-ab02e541a3ff"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Content Hub Entity Types/Webinars/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/video_chat2.png
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200427T204316Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
