---
ID: "b871e5e3-7d57-411e-b3cf-651c93d131d3"
Parent: "56ed46ac-0f58-416f-9d09-683e39825b27"
Template: "56ed46ac-0f58-416f-9d09-683e39825b27"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Global Pages/Article Page/__Standard Values
DB: master
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Type: Checklist
  Value: "{D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171108T165829Z
