---
ID: "afea29d7-609a-4c41-8a35-bf2180cd9683"
Parent: "ede537b6-698b-4b6e-b2ce-536dbdc7247a"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200122T193215Z
