---
ID: "8d967bcc-4486-46ee-badb-b47e0b97298e"
Parent: "84ff7d07-a948-4c9c-a173-f90c26e433af"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Rendering Variants/Page Content/Services
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200212T115826Z
