---
ID: "2d0256e2-7ac7-4281-8ebd-0b66be910607"
Parent: "c6928ec4-a028-4e0b-b2c8-8bbb6e55879b"
Template: "341738aa-44fe-490e-90ff-7010a3c2463b"
Path: /sitecore/system/Settings/Feature/Demo Shared SXA Sites/SitecoreDemo/XA/Sitecore Demo Extensions/Configure Indexes Post Step
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1400
- ID: "c0a5bd91-e658-46ce-b631-77ce337d8e6e"
  Hint: Script
  Type: Treelist
  Value: "{15F738E4-75D8-47C6-8F00-50F3FAB96C55}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191002T221745Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
